### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by karlfloersch** [cryptoeconomics-study/website#6]
The website is a GitBook, and GitBook has has good support for multiple languages. It would be great to get this set up as soon as possible so it's straightforward for people to contribute translations.

Here's a little resource for adding it-- https://toolchain.gitbook.com/languages.html

I'll do this myself at some point but if anyone wants to pick it up feel free 😊

**Comment by thibmeu** [comment]
Multiple things could still be done to improve both user and developer experience
+ Have a default homepage
+ Adding a language selector
+ Shared assets and code for the whole book

**Comment by WizardOfAus** [comment]
@karlfloersch I think you created and then accidentally deleted the hacktoberfest tag for the other issue. Would be great to add the tag for this issue as it is also a good first issue and a low learning curve for people new to Git and Gitbooks :)

**Comment by burrrata** [comment]
Closing this as we now have a new website that also has multi language support, but different language support. Open Issue for that here
- https://github.com/cryptoeconomics-study/dao/issues/6
